apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-scheduler
  labels:
    app: calendar
    release: {{ .Release.Name }}
    component: scheduler
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: calendar
    release: {{ .Release.Name }}
    component: scheduler
