apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-api
  labels:
    app: calendar
    release: {{ .Release.Name }}
    component: api
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.api.servicePort }}
      targetPort: http
    - name: grpc
      port: {{ .Values.api.grpcPort }}
      targetPort: grpc
  selector:
    app: calendar
    release: {{ .Release.Name }}
    component: api
