version: '3.7'

networks:
  otus-calendar:
    driver: bridge

services:
  calendar-postgres:
    container_name: otus_calendar_postgres
    image: postgres:12.2
    restart: always
    networks:
      - otus-calendar
    environment:
      PGDATA: /var/lib/postgresql/calendar
      POSTGRES_USER: intranet
      POSTGRES_PASSWORD: password
      POSTGRES_DB: calendar
      POSTGRES_PORT: 5432
    ports:
      - 5539:5432
    volumes:
      - pg_otus_calendar_data:/var/lib/postgresql/calendar
  
  rabbitmq:
    image: rabbitmq:3-management
    container_name: otus_calendar_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pg_otus_calendar_data:
