logger:
  level: info
  format: text

server:
  host: 0.0.0.0
  port: 8888

grpc:
  port: 50051

storage:
  type: sql  # available: memory | sql

db:
  host: localhost
  port: 5539
  user: intranet
  password: password
  dbname: calendar
  sslmode: disable
  max_open_conns: 10
